#!/usr/bin/env python3
"""Render the human-readable catalog from data/catalog.csv."""

from __future__ import annotations

import csv
from collections import Counter
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
CATALOG = ROOT / "data" / "catalog.csv"
OUTPUT = ROOT / "CATALOG.md"

SECTIONS = (
    ("core", "Core mechanistic-interpretability work"),
    ("safety-application", "Direct safety applications"),
    ("foundation", "Foundations"),
    ("peripheral", "Peripheral but decision-relevant work"),
)

PRIORITY_ORDER = {"essential": 0, "high": 1, "normal": 2, "reference": 3}


def md_escape(value: str) -> str:
    return value.replace("|", "\\|").replace("\n", " ").strip()


def artifact_links(row: dict[str, str]) -> str:
    links = []
    for field, label in (("pdf_url", "pdf"), ("code_url", "code"), ("data_url", "data/model")):
        if row.get(field, "").strip():
            links.append(f"[{label}]({row[field].strip()})")
    return " · ".join(links) or "—"


with CATALOG.open(newline="", encoding="utf-8") as handle:
    rows = list(csv.DictReader(handle))

rows.sort(
    key=lambda row: (
        PRIORITY_ORDER.get(row["priority"], 99),
        -int(row["year"]),
        row["title"].casefold(),
    )
)

scope_counts = Counter(row["scope"] for row in rows)
stage_counts = Counter(row["review_stage"] for row in rows)
kind_counts = Counter(row["kind"] for row in rows)

lines = [
    "# Research Catalog",
    "",
    "<!-- Generated by scripts/render_catalog.py; edit data/catalog.csv instead. -->",
    "",
    "Snapshot date: **2026-07-12**",
    "",
    f"The catalog currently contains **{len(rows)}** sources. Inclusion and review state are separate: a discovered source is not yet established evidence.",
    "",
    "## Current review status",
    "",
    "| Dimension | Counts |",
    "| --- | --- |",
    "| Scope | " + ", ".join(f"`{key}` {value}" for key, value in sorted(scope_counts.items())) + " |",
    "| Review stage | " + ", ".join(f"`{key}` {value}" for key, value in sorted(stage_counts.items())) + " |",
    "| Source kind | " + ", ".join(f"`{key}` {value}" for key, value in sorted(kind_counts.items())) + " |",
    "",
]

for scope, heading in SECTIONS:
    section_rows = [row for row in rows if row["scope"] == scope]
    lines.extend(
        [
            f"## {heading}",
            "",
            "| Year | Source | Kind/status | Topics | Stage | Artifacts | Why it is here |",
            "| ---: | --- | --- | --- | --- | --- | --- |",
        ]
    )
    for row in section_rows:
        title = md_escape(row["title"])
        source = f"[{title}]({row['canonical_url']}) <br><sub>`{row['id']}`</sub>"
        license_name = (row.get("license") or "").strip()
        artifact_status = (row.get("artifact_status") or "").strip()
        qualifiers = [row["publication_status"], license_name, artifact_status]
        qualifier_text = " · ".join(md_escape(item) for item in qualifiers if item)
        kind = f"{md_escape(row['kind'])}<br><sub>{qualifier_text}</sub>"
        topics = "<br>".join(f"`{md_escape(topic)}`" for topic in row["topics"].split("|"))
        lines.append(
            "| "
            + " | ".join(
                [
                    row["year"],
                    source,
                    kind,
                    topics,
                    f"`{row['review_stage']}`",
                    artifact_links(row),
                    md_escape(row["relevance"]),
                ]
            )
            + " |"
        )
    if not section_rows:
        lines.append("| — | No entries yet | — | — | — | — | — |")
    lines.append("")

OUTPUT.write_text("\n".join(lines), encoding="utf-8")
print(f"Rendered {len(rows)} entries to {OUTPUT.relative_to(ROOT)}")
