#!/usr/bin/env python3
"""Render a minimal BibTeX bibliography from screened papers and articles."""

from __future__ import annotations

import csv
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
CATALOG = ROOT / "data" / "catalog.csv"
OUTPUT = ROOT / "BIBLIOGRAPHY.bib"
INCLUDED_KINDS = {"paper", "article", "book"}


def bib_value(value: str) -> str:
    return value.replace("\\", "\\textbackslash{}").replace("{", "\\{").replace("}", "\\}")


def citation_key(entry_id: str) -> str:
    return re.sub(r"[^A-Za-z0-9:_-]", "-", entry_id)


with CATALOG.open(newline="", encoding="utf-8") as handle:
    rows = [row for row in csv.DictReader(handle) if row["kind"] in INCLUDED_KINDS]

rows.sort(key=lambda row: (int(row["year"]), row["title"].casefold()))
blocks = [
    "% Generated by scripts/render_bibliography.py; edit data/catalog.csv instead.",
    "% Minimal URL-based records are intentional; use the canonical source for venue-specific BibTeX.",
    "",
]

for row in rows:
    authors = " and ".join(part.strip() for part in row["authors"].split(";") if part.strip())
    entry_type = "article" if row["publication_status"] == "peer-reviewed" else "misc"
    fields = [
        ("title", row["title"]),
        ("author", authors),
        ("year", row["year"]),
        ("url", row["canonical_url"]),
    ]
    if row.get("venue", "").strip():
        fields.append(("note", row["venue"].strip()))
    blocks.append(f"@{entry_type}{{{citation_key(row['id'])},")
    for index, (name, value) in enumerate(fields):
        comma = "," if index < len(fields) - 1 else ""
        blocks.append(f"  {name} = {{{bib_value(value)}}}{comma}")
    blocks.extend(["}", ""])

OUTPUT.write_text("\n".join(blocks), encoding="utf-8")
print(f"Rendered {len(rows)} works to {OUTPUT.relative_to(ROOT)}")
